.TH i3-dtags 1 "2014" "" "User Manual"
.SH NAME
i3-dtags \- dynamic tags for i3wm
.SH SYNOPSIS
i3-dtags.sh
.SH DESCRIPTION
Run a dmenu instance with the list of currently opened tags.  You can then type
in the name of the tag you want to get in.
.br
This software also provides the \fBi3-dtags\fR executable that is needed for
the shell script to run but you should not start it alone because it is reading
a JSON string on stdin that the \fBi3-dtags.sh\fR will take care of.
.SH AUTHOR
Romain Porte <microjoe@mailoo.org>
.SH COPYRIGHT
Copyright (C) 2014  Romain Porte.  Licensed under WTFPL.
.br
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
